### PR TITLE
jsonwebtoken upgraded to fix security issue:  

### PR DESCRIPTION
**Pull request by chrisvoo**
Please refer to https://nodesecurity.io/advisories/566

### CODE REVIEW

**Comment by johanstokking** [comment]
Thanks. Seems like CI is failing, again on dependencies. Can you check?

**Comment by chrisvoo** [comment]
It seems now that a couple of tests (`applications.test.js` and `handler.test.js`) are failing in the same place, but they seem to fail also for the old `package.json` version in master, so I don't know if I'm doing something wrong. I get the same errors as CI has also in local.

     14 UNAVAILABLE: Connect Failed
      
      at Object.<anonymous>.exports.createStatusError (node_modules/grpc/src/common.js:87:15)
      at Object.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:1188:28)
      at InterceptingListener.Object.<anonymous>.InterceptingListener._callNext (node_modules/grpc/src/client_interceptors.js:564:42)
      at InterceptingListener.Object.<anonymous>.InterceptingListener.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:614:8)
      at callback (node_modules/grpc/src/client_interceptors.js:841:24)

**Comment by johanstokking** [comment]
Looping in @kschiffer to have a look!

**Comment by johanstokking** [comment]
@kschiffer what is the status?

**Comment by kschiffer** [comment]
Hi @chrisvoo, thanks for your submission. We have merged a fix for the failing CI. Could you rebase your branch on `master`? After that we can merge.

**Comment by chrisvoo** [comment]
Thanks, CI seems to work, even if my tests in local seems to fail, maybe I miss something. Using `npm`, the process was unable to find `node-pre-gyp`, so I manually installed it.

**Comment by kschiffer** [comment]
Hi @chrisvoo, thanks for the update. I cannot recreate the issue with `node-pre-gyp`. May I ask you what exact command resulted in `npm` saying it was unable to find the package?
Everything else looks good to me now.

Concerning the tests: these depend on a docker container of the TTN Stack running. We will resolve this dependency in the v3 SDK.

**Comment by chrisvoo** [comment]
Hi @kschiffer,
it said `node-gyp: command not found`, didn't have this problem with yarn instead.

**Review by kschiffer — APPROVED** [review]
LGTM

**Comment by johanstokking** [comment]
Thanks @chrisvoo

**Pull request merged**
